---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: dev-clusters-placement
  namespace: open-cluster-management
spec:
  clusterSets:
    - dev-clusters
    - remote-clusterset
